language: cpp

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

matrix:
  include:
    # g++
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5 CXXFLAGS=-O2
      script:
        - export CXX="$COMPILER"
        - make test
        - make examples
    # clang++
    - addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
      env: COMPILER=clang++-3.8 CXXFLAGS=-O2
      script:
        - export CXX="$COMPILER"
        - make test
        - make examples
    # g++ coverage
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      before_install:
        - pip install --user cpp-coveralls
      env: COMPILER=g++-5 CXXFLAGS="--coverage"
      script:
        - export CXX="$COMPILER"
        - make test
      after_success:
        - coveralls -b . --include range.hpp --gcov-options '\-lp'
